src/LodgerPms.UI.Site/Controllers/DepartmentController.cs
using System;
using LodgerPms.Application.Interfaces;
using LodgerPms.Application.ViewModels.Deparments;
using LodgerPms.Domain.Core.Notifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using LodgerPms.Application.Interfaces.Departments;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data;
using System.Linq;
using LodgerPms.Application.Services.Departments;
using Microsoft.AspNetCore.Mvc.Rendering;
using LodgerPms.UI.Site.ViewModel;

namespace LodgerPms.UI.Site.Controllers
{
    [Authorize]
    public class DepartmentController : BaseController
    {
        private readonly IDeparmentAppService _departmentAppService;
        private readonly IDepartmentGroupAppService _departmentGroupAppService;

        public DepartmentController(IDeparmentAppService DepartmentAppService, 
            IDomainNotificationHandler<DomainNotification> notifications,
             IDepartmentGroupAppService departmentGroupAppService) 
            : base(notifications)
        {
            _departmentAppService = DepartmentAppService;
            _departmentGroupAppService = departmentGroupAppService;
        }


        #region Department

        [HttpGet]
        [AllowAnonymous]
        [Route("Department-management/list-all")]
        public IActionResult Index()
        {

            var model = new DepartmentListModel();
            var g = _departmentGroupAppService.GetAll().Select(x => new SelectListItem { Value = x.Id, Text=x.Description });
            model.DepartmentGroups = g.ToList();
            model.Departments = _departmentAppService.GetAll().ToList();

            return View(model);
        }
        [HttpPost]
        [AllowAnonymous]
        [Route("Department-management/list-all")]
        public IActionResult Index(string searchString, string DepartmentType)
        {
            var departments = _departmentAppService.GetAll();
           

            if (!String.IsNullOrEmpty(searchString))
            {
                departments = departments.Where(d => d.Description.Contains(searchString));
            }

            return View(departments.ToList());
        }
       

        [HttpGet]
        [AllowAnonymous]
        [Route("Department-management/Department-details/{id:guid}")]
        public IActionResult Details(string id=null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var DepartmentViewModel = _departmentAppService.GetById(id);

            if (DepartmentViewModel == null)
            {
                return NotFound();
            }

            return View(DepartmentViewModel);
        }

        [HttpGet]
        [Authorize(Policy = "CanWriteDepartmentData")]
        [Route("Department-management/register-new")]
        public IActionResult Create()
        {
            var groups = _departmentGroupAppService.GetAll()
                .Select(x=> new SelectListItem {
                    Value= x.Id,
                    Text =  x.Description
                }).ToList();

            var model = new DepartmentViewModel();
            model.DepartmentGroups = groups;
            return View(model);
        }

        [HttpPost]
        [Authorize(Policy = "CanWriteDepartmentData")]
        [Route("Department-management/register-new")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(DepartmentViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var g = _departmentGroupAppService.FindById(model.DepartmentGroupId);
            model.DepartmentGroup = g;
            _departmentAppService.Register(model);

            if (IsValidOperation())
                ViewBag.Sucesso = "Department Registered!";

            var groups = _departmentGroupAppService.GetAll()
               .Select(x => new SelectListItem
               {
                   Value = x.Id,
                   Text = x.Description
               }).ToList();


            model.DepartmentGroups = groups;

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "CanWriteDepartmentData")]
        [Route("Department-management/edit-Department/{id:guid}")]
        public IActionResult Edit(string id=null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var DepartmentViewModel = _departmentAppService.GetById(id);

            if (DepartmentViewModel == null)
            {
                return NotFound();
            }
            var groups = _departmentGroupAppService.GetAll()
             .Select(x => new SelectListItem
             {
                 Value = x.Id,
                 Text = x.Description
             }).ToList();
            DepartmentViewModel.DepartmentGroups = groups;
            return View(DepartmentViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "CanWriteDepartmentData")]
        [Route("Department-management/edit-Department/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(DepartmentViewModel DepartmentViewModel)
        {
            if (!ModelState.IsValid) return View(DepartmentViewModel);

            _departmentAppService.Update(DepartmentViewModel);

            if (IsValidOperation())
                ViewBag.Sucesso = "Department Updated!";

            var groups = _departmentGroupAppService.GetAll()
            .Select(x => new SelectListItem
            {
                Value = x.Id,
                Text = x.Description
            }).ToList();
            DepartmentViewModel.DepartmentGroups = groups;

            return View(DepartmentViewModel);
        }

        [HttpGet]
        [Authorize(Policy = "CanRemoveDepartmentData")]
        [Route("Department-management/remove-Department/{id:guid}")]
        public IActionResult Delete(string  id=null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var DepartmentViewModel = _departmentAppService.GetById(id);

            if (DepartmentViewModel == null)
            {
                return NotFound();
            }

            return View(DepartmentViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Policy = "CanRemoveDepartmentData")]
        [Route("Department-management/remove-Department/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id=null)
        {
            _departmentAppService.Remove(id);

            if (!IsValidOperation()) return View(_departmentAppService.GetById(id));

            ViewBag.Sucesso = "Department Removed!";
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [Route("Department-management/Department-history/{id:guid}")]
        public JsonResult History(string  id=null)
        {
            var DepartmentHistoryData = _departmentAppService.GetAllHistory(id);
            return Json(DepartmentHistoryData);
        }


        #endregion

       
    }
}

src/LodgerPms.UI.Site/Controllers/FolioPatternController.cs
using System;
using LodgerPms.Application.Interfaces;
using LodgerPms.Application.ViewModels.Deparments;
using LodgerPms.Domain.Core.Notifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data;
using System.Linq;

using Microsoft.AspNetCore.Mvc.Rendering;
using LodgerPms.UI.Site.ViewModel;
using LodgerPms.Application.Interfaces.Departments;

namespace LodgerPms.UI.Site.Controllers
{
    [Authorize]
    public class FolioPatternController : BaseController
    {
        
        private readonly IFolioPatternAppService _folioPatternAppService;

        public FolioPatternController(IFolioPatternAppService folioPatternAppService, 
            IDomainNotificationHandler<DomainNotification> notifications ) 
            : base(notifications)
        {
            _folioPatternAppService = folioPatternAppService; 
        } 

        #region FolioPattern Group

        [HttpGet]
        [AllowAnonymous]
        [Route("FolioPattern-management/list-all")]
        public IActionResult Index()
        {
            return View(_folioPatternAppService.GetAll());
        }
        [HttpPost]
        [AllowAnonymous]
        [Route("FolioPattern-management/list-all")]
        public IActionResult Index(string searchString)
        {
            var FolioPatterns = _folioPatternAppService.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                FolioPatterns = FolioPatterns.Where(d => d.Description.Contains(searchString));
            }

            return View(FolioPatterns.ToList());
        }


        [HttpGet]
        [AllowAnonymous]
        [Route("FolioPattern-management/FolioPattern-details/{id:guid}")]
        public IActionResult Details(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpGet]
     //   [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/register-new")]
        public IActionResult  Create()
        {
            return View();
        }

        [HttpPost]
      //  [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/register-new")]
        [ValidateAntiForgeryToken]
        public IActionResult  Create(FolioPatternViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            _folioPatternAppService.Register(model);

            if (IsValidOperation())
                ViewBag.Sucesso = "FolioPattern Registered!";

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/edit-FolioPattern/{id:guid}")]
        public IActionResult  Edit(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/edit-FolioPattern/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult  Edit(FolioPatternViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            _folioPatternAppService.Update(model);

            if (IsValidOperation())
                ViewBag.Sucesso = "FolioPattern Updated!";

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "CanRemoveFolioPatternData")]
        [Route("FolioPattern-management/remove-FolioPattern/{id:guid}")]
        public IActionResult  Delete(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Policy = "CanRemoveFolioPatternData")]
        [Route("FolioPattern-management/remove-FolioPattern/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult  DeleteConfirmed(string id = null)
        {
            _folioPatternAppService.Remove(id);

            if (!IsValidOperation()) return View(_folioPatternAppService.GetById(id));

            ViewBag.Sucesso = "FolioPattern Group Removed!";
            return RedirectToAction("Index");
        }

        //[AllowAnonymous]
        //[Route("FolioPattern-management/FolioPattern-history/{id:guid}")]
        //public JsonResult  History(string id = null)
        //{
        //    var FolioPatternHistoryData = _folioPatternAppService.GetAllHistory(id);
        //    return Json(FolioPatternHistoryData);
        //}


        #endregion
    }
}

src/LodgerPms.UI.Site/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Access Denied";
}

<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">You don't have enough access.</h2>

src/LodgerPms.UI.Site/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LodgerPms.UI.Site</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LodgerPms.UI.Site</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - LodgerPms.UI.Site</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/LodgerPms.UI.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LodgerPms Project</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/logo.png" style="width: 170px; height: 37px" alt="LodgerPms Project" /></a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Maintenance <span class="glyphicon glyphicon-cog"></span> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="DepartmentGroup" asp-action="Index">Departments Group</a></li>
                            <li><a asp-area="" asp-controller="Department" asp-action="Index">Departments</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a asp-area="" asp-controller="FolioPattern" asp-action="Index">Folio Pattern</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                     
                    @await Html.PartialAsync("_LoginPartial")
</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>LodgerPms Project - Version 1.0</p>
            <p>Developed by - <a href="http://lodgerpms.com/" target="_blank">lodgerpms.com</a> - This is an open-source project <a href="https://github.com/LodgerPms" target="_blank">LodgerPms GitHub</a></p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>