src/LodgerPms.UI.Site/Controllers/FolioPatternController.cs
using System;
using LodgerPms.Application.Interfaces;
using LodgerPms.Application.ViewModels.Deparments;
using LodgerPms.Domain.Core.Notifications;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data;
using System.Linq;

using Microsoft.AspNetCore.Mvc.Rendering;
using LodgerPms.UI.Site.ViewModel;
using LodgerPms.Application.Interfaces.Departments;

namespace LodgerPms.UI.Site.Controllers
{
    [Authorize]
    public class FolioPatternController : BaseController
    {
        
        private readonly IFolioPatternAppService _folioPatternAppService;

        public FolioPatternController(IFolioPatternAppService folioPatternAppService, 
            IDomainNotificationHandler<DomainNotification> notifications ) 
            : base(notifications)
        {
            _folioPatternAppService = folioPatternAppService; 
        } 

        #region FolioPattern Group

        [HttpGet]
        [AllowAnonymous]
        [Route("FolioPattern-management/list-all")]
        public IActionResult Index()
        {
            return View(_folioPatternAppService.GetAll());
        }
        [HttpPost]
        [AllowAnonymous]
        [Route("FolioPattern-management/list-all")]
        public IActionResult Index(string searchString)
        {
            var FolioPatterns = _folioPatternAppService.GetAll();

            if (!String.IsNullOrEmpty(searchString))
            {
                FolioPatterns = FolioPatterns.Where(d => d.Description.Contains(searchString));
            }

            return View(FolioPatterns.ToList());
        }


        [HttpGet]
        [AllowAnonymous]
        [Route("FolioPattern-management/FolioPattern-details/{id:guid}")]
        public IActionResult Details(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpGet]
     //   [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/register-new")]
        public IActionResult  Create()
        {
            return View();
        }

        [HttpPost]
      //  [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/register-new")]
        [ValidateAntiForgeryToken]
        public IActionResult  Create(FolioPatternViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            _folioPatternAppService.Register(model);

            if (IsValidOperation())
                ViewBag.Sucesso = "FolioPattern Registered!";

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/edit-FolioPattern/{id:guid}")]
        public IActionResult  Edit(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpPost]
        [Authorize(Policy = "CanWriteFolioPatternData")]
        [Route("FolioPattern-management/edit-FolioPattern/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult  Edit(FolioPatternViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            _folioPatternAppService.Update(model);

            if (IsValidOperation())
                ViewBag.Sucesso = "FolioPattern Updated!";

            return View(model);
        }

        [HttpGet]
        [Authorize(Policy = "CanRemoveFolioPatternData")]
        [Route("FolioPattern-management/remove-FolioPattern/{id:guid}")]
        public IActionResult  Delete(string id = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            var FolioPatternViewModel = _folioPatternAppService.GetById(id);

            if (FolioPatternViewModel == null)
            {
                return NotFound();
            }

            return View(FolioPatternViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Policy = "CanRemoveFolioPatternData")]
        [Route("FolioPattern-management/remove-FolioPattern/{id:guid}")]
        [ValidateAntiForgeryToken]
        public IActionResult  DeleteConfirmed(string id = null)
        {
            _folioPatternAppService.Remove(id);

            if (!IsValidOperation()) return View(_folioPatternAppService.GetById(id));

            ViewBag.Sucesso = "FolioPattern Group Removed!";
            return RedirectToAction("Index");
        }

        //[AllowAnonymous]
        //[Route("FolioPattern-management/FolioPattern-history/{id:guid}")]
        //public JsonResult  History(string id = null)
        //{
        //    var FolioPatternHistoryData = _folioPatternAppService.GetAllHistory(id);
        //    return Json(FolioPatternHistoryData);
        //}


        #endregion
    }
}

src/LodgerPms.UI.Site/ViewComponents/SummaryViewComponent.cs
using System.Threading.Tasks;
using LodgerPms.Domain.Core.Notifications;
using Microsoft.AspNetCore.Mvc;

namespace LodgerPms.UI.Site.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly IDomainNotificationHandler<DomainNotification> _notifications;

        public SummaryViewComponent(IDomainNotificationHandler<DomainNotification> notifications)
        {
            _notifications = notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult((_notifications.GetNotifications()));
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

src/LodgerPms.UI.Site/Views/FolioPattern/Create.cshtml
@model LodgerPms.Application.ViewModels.Deparments.FolioPatternViewModel

@{
    ViewData["Title"] = "Register new Folio Pattern";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <hr />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />
       
        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/LodgerPms.UI.Site/Views/FolioPattern/Delete.cshtml
@model LodgerPms.Application.ViewModels.Deparments.FolioPatternViewModel

@{
    ViewData["Title"] = "Delete Folio Pattern";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Delete">
    <vc:summary />

    <h3>Are you sure you want to delete the @Model.Description?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Code)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Code)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
            
        </dl>


        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

src/LodgerPms.UI.Site/Views/FolioPattern/Details.cshtml
@model LodgerPms.Application.ViewModels.Deparments.FolioPatternViewModel

@{
    ViewData["Title"] = "Folio Pattern Details";
}

<h2>@ViewData["Title"]</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
    
        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a> 
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

src/LodgerPms.UI.Site/Views/FolioPattern/Edit.cshtml
@model LodgerPms.Application.ViewModels.Deparments.FolioPatternViewModel

@{
    ViewData["Title"] = "Edit Folio Pattern";
}

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <hr />

        <input type="hidden" asp-for="Id" />

        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:summary />

        <div class="form-group">
            <label asp-for="Code" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/LodgerPms.UI.Site/Views/FolioPattern/Index.cshtml
@model IEnumerable<LodgerPms.Application.ViewModels.Deparments.FolioPatternViewModel>

@{
    ViewData["Title"] = "Folio Pattern Management";

   
}

<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />

<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="glyphicon glyphicon-plus-sign"></span> Register New
                </a>
            </div>
            <div class="pull-right">

                <form asp-controller="FolioPattern" asp-action="Index" method="post">                   
                    <p>
                        <input type="text" name="SearchString" placeholder="Description">
                        <input type="submit" value="Filter" class="btn btn-default"/>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>
<br />

<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Code)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                        
                    <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                        <span class="glyphicon glyphicon-search"></span>
                    </a>
                        
                    <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    
                    <button type="button" class="btn btn-purple viewbutton" title="History" data-id="@item.Id" data-toggle="modal" data-target="#DepartmentHistory">
                        <span class="glyphicon glyphicon-time"></span>
                    </button>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>

<div class="modal fade" id="DepartmentHistory" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Department Group Data History</h4>
            </div>
            <div class="modal-body">
                <p id="DepartmentHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        $(".viewbutton").on("click", function() {
            var DepartmentId = $(this).data('id');
            $.ajax({
                url: "http://localhost:52346/Department-management/Department-history/" + DepartmentId,
                //url: "http://LodgerPmsproject.azurewebsites.net/Department-management/Department-history/" + DepartmentId,
                cache: false
            }).done(function(data) {
                var formatHtml = "<table class='table table-striped'>";
                formatHtml += "<thead><th>Action</th><th>When</th><th>Id</th><th>Name</th><th>E-mail</th><th>Birth Date</th><th>By User</th></thead>";

                for (var i = 0; i < data.length; i++) {
                    var change = data[i];
                    formatHtml += "<tr>";
                    formatHtml += "<td>" + change.action + "</td>";
                    formatHtml += "<td>" + change.when + "</td>";
                    formatHtml += "<td>" + change.id + "</td>";
                    formatHtml += "<td>" + change.name + "</td>";
                    formatHtml += "<td>" + change.email + "</td>";
                    formatHtml += "<td>" + change.birthDate + "</td>";
                    formatHtml += "<td>" + change.who + "</td>";
                    formatHtml += "</tr>";
                }
                formatHtml += "</table>";
                $("#DepartmentHistoryData").html(formatHtml);
            });
        });
</script>
}